///////////////////////////////////////////////////////////
//  AccommodationType.cs
//  Implementation of the Class AccommodationType
//  Generated by Enterprise Architect
//  Created on:      06-Jun-2017 00:33:18
//  Original author: Alexis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace System {
	public class AccommodationType {

		private int id;
		private string name;
		public List<Accommodation> m_Accommodation;

		public AccommodationType(){

		}

		~AccommodationType(){

		}

		public int Id{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string Name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

	}//end AccommodationType

}//end namespace System