///////////////////////////////////////////////////////////
//  Comment.cs
//  Implementation of the Class Comment
//  Generated by Enterprise Architect
//  Created on:      06-Jun-2017 00:33:18
//  Original author: Alexis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace System {
	public class Comment {

		private int grade;
		private string text;
		public List<User> m_User;
		public List<Accommodation> m_Accommodation;

		public Comment(){

		}

		~Comment(){

		}

		public int Grade{
			get{
				return Grade;
			}
			set{
				Grade = value;
			}
		}

		public string Text{
			get{
				return Text;
			}
			set{
				Text = value;
			}
		}

	}//end Comment

}//end namespace System